-- Anil V1 | FINAL UNIVERSAL
-- Script By Anil | UNITED

---------------- SERVICES ----------------
local Players = game:GetService("Players")
local TextChatService = game:GetService("TextChatService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local lp = Players.LocalPlayer
if not lp then return end

---------------- CONFIG ----------------
local SPAM_LINE_LEN = 180
local WARNING_LINE_LEN = 200
local DEFAULT_DELAY = 1.5
local WARNING_DELAY = 20

---------------- OWNER ----------------
local OWNER = "akj200995"

---------------- STATE ----------------
local running = false
local locked = false
local index = 1

---------------- WORDS ----------------
local TMKX_WORDS = {
	"TMKX MAI BUS","TMKX MAI AEROPLANE","TMKX MAI TRAIN","TMKX MAI STATION",
	"TMKX MAI PHONE","TMKX MAI LAPTOP","TMKX MAI SCHOOL","TMKX MAI STUDENTS",
	"TMKX MAI TEACHERS","TMKX MAI CLASSROOM","TMKX MAI BOOKS",
	"TMKX MAI PIZZA","TMKX MAI BURGER","TMKX MAI ICECREAM",
	"TMKX MAI CAR","TMKX MAI BIKE","TMKX MAI ROAD","TMKX MAI HIGHWAY",
	"TMKX MAI ROBLOX","TMKX MAI BROOKHAVEN","TMKX MAI DELTA",
	"TMKX MAI FOOTBALL","TMKX MAI CRICKET","TMKX MAI GARDEN",
	"TMKX MAI CLOCK","TMKX MAI WATCH","TMKX MAI PEN","TMKX MAI PENCIL",
	"TMKX MAI NOTEBOOK","TMKX MAI BAG","TMKX MAI WALLET",
	"TMKX MAI CHARGER","TMKX MAI POWERBANK","TMKX MAI SPEAKER",
	"TMKX MAI HEADPHONES","TMKX MAI MIC","TMKX MAI ROUTER",
	"TMKX MAI WIFI","TMKX MAI SATELLITE","TMKX MAI SIGNAL",
	"TMKX MAI AI","TMKX MAI ROBOT","TMKX MAI FUTURE","TMKX MAI ASIAN PAINTS",
	"TMKX MAI KELA","TMKX MAI BANDAR","TMKX MAI PHOTO","TMKX MAI LENS",
	"TMKX MAI LOTION","TMKX MAI CREAM","TMKX MAI GOD","TMKX MAI DEVIL",
	"TMKX MAI SANTA","TMKX MAI PHD","TMKX MAI GRADUATION","TMKX MAI MBA",
	"TMKX MAI T-SHIRT","TMKX MAI SHIRT","TMKX MAI SHOES","TMKX MAI SNEAKERS",
	"TMKX MAI COAT","TMKX MAI DARU","TMKX MAI PED","TMKX MAI LOVE B1TE",
	"TMKX MAI ORANGE","TMKX MAI APPLE","TMKX MAI MANGO","TMKX MAI BANANA",
	"TMKX MAI CARROT","TMKX MAI CUCUMBER","TMKX MAI SALMAN KHAN",
	"TMKX MAI SRK","TMKX MAI SANJAYDUTT","TMKX MAI BOLLYWOOD",
	"TMKX MAI HOLLYWOOD","TMKX MAI TOLLYWOOD","TMKX MAI STUNT",
	"TMKX MAI RACE","TMKX MAI BRAKE","TMKX MAI MARUTI",
	"TMKX MAI FERRARI","TMKX MAI FORTUNER","TMKX MAI LAMBORGHINI",
	"TMKX MAI  PORSCHE","TMKX MAI INNOVA","TMKX MAI CREATA",
	"TMKX MAI METRO","TMKX MAI STAFF","TMKX MAI OFFICE",
	"TMKX MAI WORKERS","TMKX MAI PLUMBER","TMKX MAI REPAIRER",
	"TMKX MAI LAWYER","TMKX MAI POLICE","TMKX MAI CHOR",
	"TMKX MAI CR1MINAL","TMKX MAI DARU","TMKX MAI BEER","TMKX MAI WINE",
	"TMKX MAI BOTTLE","TMKX MAI GLASS","TMKX MAI PLATE",
	"TMKX MAI BULB","TMKX MAI WIRE","TMKX MAI ADAPTER",
	"TMKX MAI EGG","TMKX MAI HARRYPOTTER","TMKX MAI KANGAROO",
	"TMKX MAI DINOSAUR","TMKX MAI STRANGERTHINGS",
	"TMKX MAI BAMBOO","TMKX MAI WOOD","TMKX MAI PANDA",
	"TMKX MAI PLASTIC","TMKX MAI THERMOCOL","TMKX MAI THERMAL",
	"TMKX MAI TITANIC","TMKX MAI SHIP"," TMKX MAI BEWADA",
	"TMKX MAI NIBBA","TMKX MAI SPACE","TMKX MAI SUN",
	"TMKX MAI MARS","TMKX MAI SATURN","TMKX MAI MARS","TMKX MAI JUPITER",
	"TMKX MAI RED STAR","TMKX MAI GIANT STAR",
	"TMKX MAI FATHER","TMKX MAI MOTHER","TMKX MAI SISTER",
	"TMKX MAI BROTHER","TMKX MAI DADI","TMKX MAI DADA",
	"TMKX MAI PAR DADA","TMKX MAI CYCLE","TMKX MAI MOTOR",
	"TMKX MAI TURBO","TMKX MAI Anil","TMKX MAI SAB PGL",
	"TMKX MAI AMERICA","TMKX MAI INDIA","TMKX MAI RUSSIA",
	"TMKX MAI ASIA","TMKX MAI EUROPE","TMKX MAI AFRIA",
	"TMKX MAI AUSTRALIA","TMKX MAI THERMOMETER",
	"TMKX MAI ACID","TMKX MAI LAB","TMKX MAI CHEM1CALS",
	"TMKX MAI BASES","TMKX MAI HYPOTENUSE",
	"TMKX MAI RIGHTANGLE","TMKX MAI SQURE",
	"TMKX MAI CIRCLE","TMKX MAI RECTANGLE",
	"TMKX MAI COCKROACH","TMKX MAI BUTTERFLY",
	"TMKX MAI DOG","TMKX MAI CAT","TMKX MAI DOLPHIN",
	"TMKX MAI WHALE","TMKX MAI SHARK","TMKX MAI SEAHORSE",
	"TMKX MAI MERMAID","TMKX MAI JELLYFISH",
	"TMKX MAI ROD","TMKX MAI KHAMBA","TMKX MAI P1LLAR",
	"TMKX MAI BR1DGE","TMKX MAI COMPASS",
	"TMKX MAI WATCH","TMKX MAI BANK","TMKX MAI CLUB",
	"TMKX MAI DENTIST","TMKX MAI HOSPITAL","TMKX MAI DOCTOR",
	"TMKX MAI NURSE","TMKX MAI PAT1ENT","TMKX MAI VISITOR",
	"TMKX MAI CL1ENT","TMKX MAI PURGATORY","TMKX MAI BERMUDA",
	"TMKX MAI KALAHARI","TMKX MAI BR RANK","TMKX MAI CS RANK",
	"TMKX MAI LONEWOLF","TMKX MAI TRAN1NG",
	"TMKX MAI MICKEY MOUSE","TMKX MAI DORAEMON",
	"TMKX MAI NOB1TA","TMKX MAI SHIZUKA","TMKX MAI G1AN",
	"TMKX MAI SUNEO","TMKX MAI SHINCHAN",
	"TMKX MAI PERMAN","TMKX MAI BHOSADMAN",
	"TMKX MAI SP1DERMAN","TMKX MAI BATMAN",
	"TMKX MAI CAPTAINAMERICA","TMKX MAI THOR",
	"TMKX MAI VENOM","TMKX MAI SUPERMAN",
	"TMKX MAI TV","TMKX MAI FRIDGE","TMKX MAI INVERTER",
	"TMKX MAI GENERATOR","TMKX MAI 500RS","TMKX MAI 100RS",
	"TMKX MAI 200","TMKX MAI UN1TEDKALAND",
	"TMKX MAI 10 BNDE","TMKX MAI KINGFISHER",
	"TMKX MAI O1D MONK","TMKX MAI B0T","TMKX MAI N00B",
	"TMKX MAI ATANKWAD","TMKX MAI REP","TMKX MAI ATTACK",
	"TMKX MAI GLASSES"," TMKX MAI MINNOR","TMKX MAI SUNGLASSES",
	"TMKX MAI PR1NTER","TMKX MAI BASS","TMKX MAI VOLUME",
	"TMKX MAI MR BEAST","TMKX MAI PEWDIEPIE","TMKX MAI JOHNCINA",
	"TMKX MAI CURTAIN","TMKX MAI SOFA","TMKX MAI BEDSHEET",
	"TMKX MAI BED","TMKX MAI PILLOW","TMKX MAI DESIGNER",
	"TMKX MAI RENOVATION","TMKX MAI CRASHLANDING",
	"TMKX MAI SIGMA","TMKX MAI ALPHA","TMKX MAI GIGA",
	"TMKX MAI TESTOSTERONE"," TMKX MAI ESTROGEN",
	"TMKX MAI BELL","TMKX MAI DOOR","TMKX MAI FLAT",
	"TMKX MAI V1LLA","TMKX MAI LUXURY","TMKX MAI BUNGLO",
	"TMKX MAI H3ART","TMKX MAI L1VER","TMKX MAI K1DNEY",
	"TMKX MAI DAM","TMKX MAI PRESSURE","TMKX MAI BLACKHOLE",
	"TMKX MAI ROCKET","TMKX MAI SPACESHIP","TMKX MAI ASTRONAUT",
	"TMKX MAI CNG","TMKX MAI PETROL","TMKX MAI WATER",
	"TMKX MAI D1SEAL","TMKX MAI COKE","TMKX MAI DEW",
	"TMKX MAI SPRITE","TMKX MAI FACTORY","TMKX MAI COMPANY",
	"TMKX MAI GAS","TMKX MAI HELIUM","TMKX MAI ENERGY",
	"TMKX MAI ELECTRICITY","TMKX MAI RADIO","TMKX MAI RADIATION",
	"TMKX MAI SHOK","TMKX MAI FREQUENCY","TMKX MAI ACTIVE",
	"TMKX MAI NITROGEN","TMKX MAI SULPHUR","TMKX MAI C02",
	"TMKX MAI H20","TMKX MAI S2S0","TMKX MAI A²",
	"TMKX MAI TALWINDER","TMKX MAI HONEY SINGH",
	"TMKX MAI BADSHAH","TMKX MAI RAP","TMKX MAI MELODY",
	"TMKX MAI GUITAR","TMKX MAI PIANO","TMKX MAI DRUM",
	"TMKX MAI BENCH","TMKX MAI WHITEBOARD",
	"TMKX MAI BLACKBOARD","TMKX MAI CHALK","TMKX MAI DUSTER",
	"TMKX MAI DIAMOND","TMKX MAI GOLD","TMKX MAI INVESTMENT",
	"TMKX MAI LOAN","TMKX MAI FAN","TMKX MAI TUBE",
	"TMKX MAI PIPE","TMKX MAI WASH","TMKX MAI SOAP",
	"TMKX MAI SHAMPOO","TMKX MAI DANDA","TMKX MAI PAN",
	"TMKX MAI STOVE","TMKX MAI BLUEDRUM",
	"TMKX MAI CONSTRUCTION","TMKX MAI BULDOGER",
	"TMKX MAI JCB","TMKX MAI FARMHOUSE","TMKX MAI HELIPAD",
	"TMKX MAI SITE","TMKX MAI CONTRACT","TMKX MAI FARMER",
	"TMKX MAI FARM","TMKX MAI FARMING","TMKX MAI BUILDING",
	"TMKX MAI PROJECT","TMKX MAI AMIR","TMKX MAI GARIB",
	"TMKX MAI CHINAL","TMKX MAI HIJRA"," TMKX MAI 6KKA",
	"TMKX MAI FREEZY","TMKX MAI BOMB","TMKX MAI HATTHI",
	"TMKX MAI MONEY","TMKX MAI PARTICIAN",
	" TMKX MAI DIWALI","TMKX MAI CHRISTMAS","TMKX MAI EID",
	"TMKX MAI CAVE","TMKX MAI MOUNTAIN","TMKX MAI FOUNTAIN",
	"TMKX MAI CRUISE","TMKX MAI BEACH","TMKX MAI OCEAN",
	"TMKX MAI SEA","TMKX MAI SUNSCREEN","TMKX MAI WIRE",
	"TMKX MAI CURRENT","TMKX MAI GHAR","TMKX MAI MANSION",
	"TMKX MAI FRAME","TMKX MAI SAB",
-- ===== TV KE BAAD ADD KI GAYI LIST (UNCHANGED WORDS) =====
"TMKX MAI RAYS",
"TMKX MAI OXYGEN",
"TMKX MAI CARBON",
"TMKX MAI DIOXIDE",
"TMKX MAI GIRL", 
"TMKX MAI BOY",
"TMKX MAI WATCHMAN",
"TMKX MAI PURSE",
"TMKX MAI TABLE",
"TMKX MAI BENCH",
"TMKX MAI BARBELL",
"TMKX MAI GYM",
"TMKX MAI TREADMILL",
"TMKX MAI DUMBELL",
"TMKX MAI WEIGHT",
"TMKX MAI POWER",
"TMKX MAI TRAINER",
"TMKX MAI MEMBERSHIP",
"TMKX MAI OWNER",
"TMKX MAI AnilKALAND",
"TMKX MAI APRIL",
"TMKX MAI JUNE",
"TMKX MAI MAY",
"TMKX MAI FEBRUARY",
"TMKX MAI JANUARY",
"TMKX MAI AUGUST",
"TMKX MAI MARCH",
"TMKX MAI SATURDAY",
"TMKX MAI MONDAY",
"TMKX MAI FRIDAY",
"TMKX MAI THUSDAY",
"TMKX MAI SUNDAY",
"TMKX MAI LULLI",
"TMKX MAI BACCHA",
"TMKX MAI PILA",
"TMKX MAI BOX",
"TMKX MAI METAL",
"TMKX MAI SILVER",
"TMKX MAI STEEL",
"TMKX MAI BRASS",
"TMKX MAI COPPER",
"TMKX MAI IRON",
"TMKX MAI CHOCO",
"TMKX MAI UTENSIL",
"TMKX MAI MOTI",
"TMKX MAI GOTA",
"TMKX MAI LOTA",
"TMKX MAI GRINDER",
"TMKX MAI BURNER",
"TMKX MAI CYCLINDER",
"TMKX MAI TRUCK",
"TMKX MAI TEMPO",
"TMKX MAI OVERLORD",
	"TMKX MAI DYNASTY",
	"TMKX MAI THRONE",
	"TMKX MAI WARZONE",
	"TMKX MAI BATTLEFIELD",
	"TMKX MAI STRIKE",
	"TMKX MAI DOMINATION",
	"TMKX MAI CONQUEST",
	"TMKX MAI SUPREMACY",
	"TMKX MAI REIGN",

	"TMKX MAI DARKNESS",
	"TMKX MAI SHADOW",
	"TMKX MAI PHANTOM",
	"TMKX MAI WRAITH",
	"TMKX MAI VORTEX",
	"TMKX MAI VOID",
	"TMKX MAI OBLIVION",
	"TMKX MAI INFERNO",
	"TMKX MAI FURY",
	"TMKX MAI CHAOS",

	"TMKX MAI CYBERCORE",
	"TMKX MAI MAINFRAME",
	"TMKX MAI FIREWALL",
	"TMKX MAI ENCRYPTION",
	"TMKX MAI DECRYPTION",
	"TMKX MAI PAYLOAD",
	"TMKX MAI BACKDOOR",
	"TMKX MAI ROOTACCESS",
	"TMKX MAI OVERCLOCK",
	"TMKX MAI PROTOCOL",

	"TMKX MAI WARLORD",
	"TMKX MAI ASSASSIN",
	"TMKX MAI MERCENARY",
	"TMKX MAI SNIPER",
	"TMKX MAI COMMANDER",
	"TMKX MAI GENERAL",
	"TMKX MAI CAPTAIN",
	"TMKX MAI SOLDIER",
	"TMKX MAI TROOPS",
	"TMKX MAI ARSENAL",

	"TMKX MAI OUTLAW",
	"TMKX MAI RENEGADE",
	"TMKX MAI VIGILANTE",
	"TMKX MAI HITMAN",
	"TMKX MAI TRACKER",
	"TMKX MAI HUNTER",
	"TMKX MAI PREDATOR",
	"TMKX MAI SURVIVOR",
	"TMKX MAI NOMAD",
	"TMKX MAI ROGUE",

	"TMKX MAI MENTALITY",
	"TMKX MAI PSYCHOLOGY",
	"TMKX MAI INSTINCT",
	"TMKX MAI REFLEX",
	"TMKX MAI DISCIPLINE",
	"TMKX MAI DETERMINATION",
	"TMKX MAI WILLPOWER",
	"TMKX MAI DOMINANCE",
	"TMKX MAI ENDURANCE",
	"TMKX MAI GRIND",

	"TMKX MAI NEURAL",
	"TMKX MAI QUANTUM",
	"TMKX MAI PARTICLE",
	"TMKX MAI WAVELENGTH",
	"TMKX MAI SPECTRUM",
	"TMKX MAI PLASMA",
	"TMKX MAI MAGNETISM",
	"TMKX MAI FUSION",
	"TMKX MAI FISSION",
	"TMKX MAI CORE",

	"TMKX MAI TIMELINE",
	"TMKX MAI PARADOX",
	"TMKX MAI DIMENSION",
	"TMKX MAI REALM",
	"TMKX MAI PORTAL",
	"TMKX MAI RIFT",
	"TMKX MAI ASCENSION",
	"TMKX MAI TRANSCEND",
	"TMKX MAI EVOLUTION",
	"TMKX MAI AWAKENING",
}

---------------- CHAT SEND ----------------
local function send(msg)
	if TextChatService.ChatVersion == Enum.ChatVersion.TextChatService then
		local ch = TextChatService.TextChannels:FindFirstChild("RBXGeneral")
		if ch then pcall(function() ch:SendAsync(msg) end) end
	else
		local ev = ReplicatedStorage:FindFirstChild("DefaultChatSystemChatEvents")
		if ev then ev.SayMessageRequest:FireServer(msg,"All") end
	end
end

---------------- PATTERN ----------------
local function makePattern(p,l)
	local s=""
	while #s<l do s=s..p end
	return s:sub(1,l)
end

---------------- NAME MATCH (USERNAME + DISPLAY NAME + PARTIAL) ----------------
local function nameMatch(input, player)
	if not input or input == "" then return false end
	input = string.lower(input)

	local uname = string.lower(player.Name)
	local dname = string.lower(player.DisplayName)

	return string.find(uname, input, 1, true) ~= nil
		or string.find(dname, input, 1, true) ~= nil
end

---------------- GUI ----------------
local gui = Instance.new("ScreenGui", lp.PlayerGui)
gui.Name = "Anil_V1"

local frame = Instance.new("Frame", gui)
frame.Size = UDim2.new(0,330,0,250)
frame.Position = UDim2.new(0.5,-165,0.5,-125)
frame.BackgroundColor3 = Color3.fromRGB(20,20,20)
frame.Active=true
frame.Draggable=true

local title = Instance.new("TextLabel",frame)
title.Size=UDim2.new(1,0,0,30)
title.Text="Anil BOT SCRIPT"
title.TextColor3=Color3.new(1,1,1)
title.BackgroundColor3=Color3.fromRGB(30,30,30)

local function box(t,y)
	local b=Instance.new("TextBox",frame)
	b.Size=UDim2.new(0.9,0,0,26)
	b.Position=UDim2.new(0.05,0,y,0)
	b.Text=t
	b.TextColor3=Color3.new(1,1,1)
	b.BackgroundColor3=Color3.fromRGB(40,40,40)
	return b
end

local targetBox=box("TARGET NAME",0.18)
local delayBox=box("DELAY",0.34)
local patternBox=box("PATTERN",0.50)

local startBtn=Instance.new("TextButton",frame)
startBtn.Size=UDim2.new(0.4,0,0,30)
startBtn.Position=UDim2.new(0.05,0,0.74,0)
startBtn.Text="START"

local stopBtn=Instance.new("TextButton",frame)
stopBtn.Size=UDim2.new(0.4,0,0,30)
stopBtn.Position=UDim2.new(0.55,0,0.74,0)
stopBtn.Text="STOP"

---------------- SPAM ----------------
local function startSpam()
	if running or locked then return end
	running=true
	index=1

	local warn="Spam starting in 20 seconds | SCRIPT BY Anil"
	send(makePattern("_",WARNING_LINE_LEN-#warn)..warn)

	task.wait(WARNING_DELAY)

	while running and not locked do
		local word=TMKX_WORDS[index]
		local target=targetBox.Text
		local free=SPAM_LINE_LEN-(#word+#target+2)
		if free<5 then free=5 end
		send(makePattern(patternBox.Text,free).." "..target.." "..word)
		index=index%#TMKX_WORDS+1
		task.wait(tonumber(delayBox.Text) or DEFAULT_DELAY)
	end
end

local function stopSpam()
	running=false
end

startBtn.MouseButton1Click:Connect(startSpam)
stopBtn.MouseButton1Click:Connect(stopSpam)

---------------- CHAT COMMAND LISTENER ----------------
local function onChat(sender,msg)
	local args=msg:split(" ")

	-- OWNER self controls
	if sender==OWNER and lp.Name==OWNER then
		if args[1]=="!start" then startSpam()
		elseif args[1]=="!stop" then stopSpam()
		elseif args[1]=="!delay" then delayBox.Text=args[2] end
	end

	-- LOCK / RELEASE (DisplayName + partial supported)
	if sender==OWNER and nameMatch(args[2], lp) then
		if args[1]=="!lock" then
			locked=true
			stopSpam()
			startBtn.Active=false
			stopBtn.Active=false
			send(makePattern("_",WARNING_LINE_LEN-27).."SCRIPT LOCKED BY Anil S1R")

		elseif args[1]=="!release" then
			locked=false
			startBtn.Active=true
			stopBtn.Active=true
			send(makePattern("_",WARNING_LINE_LEN-29).."SCRIPT UNLOCKED BY Anil S1R")
		end
	end
end

-- TextChatService
if TextChatService.ChatVersion==Enum.ChatVersion.TextChatService then
	TextChatService.MessageReceived:Connect(function(m)
		onChat(m.TextSource.Name,m.Text)
	end)
else
	lp.Chatted:Connect(function(m)
		onChat(lp.Name,m)
	end)
end

warn("Anil V1 | FINAL UNIVERSAL | LOADED")
